### PR TITLE
fix:usr:#15:Accept JSON with missing Views, Cubes or Groups

### PR DESCRIPTION
**Pull request by vrajat**
As of now, these attributes are required. Even if cubes are not required, an empty array has to be provided. This pull request allows these attributes to be skipped and the default is set to an empty array if the developer is not interested in defining these attributes.

### CODE REVIEW

**Comment by vrajat** [comment]
@adeshr Please review this PR too.

**Comment by amoghmargoor** [comment]
Looks good to me.

**Comment by adeshr** [comment]
Looks good to me too.

**Comment by vrajat** [comment]
No. Not intentionally. I'll check.

**Comment by vrajat** [comment]
@amoghmargoor if it looks good, please merge the PR. Not good practice to merge your own change ;).

The format of the commit is the 
Title (same as title of the PR

Fix #16 (Automatically closes the issue)
Description(Description of the PR) 

For e.g.:

fix:usr:Accept JSON with missing Views, Cubes or Groups

Fix #15
As of now, these attributes are required. Even if cubes are not required, an empty array has to be provided. This pull request allows these attributes to be skipped and the default is set to an empty array if the developer is not interested in defining these attributes.

**Comment by vrajat** [comment]
Oh wait. Let me rebase it

**Comment by amoghmargoor** [comment]
sure will merge it.

**Comment by vrajat** [comment]
Hitting some problems when rebasing. Give me sometime. I'll come back to this.

**Comment by vrajat** [comment]
@amoghmargoor I merged this through command line. Just couldnt get the rebase workflow to work ...

**Pull request closed without merging**
