### PR TITLE
new: user: #65: Support for SHOW DDL commands

### PR DESCRIPTION
**Pull request by adeshr**
Added show DDL statements for dataSources/views:

1. `SHOW DATASOURCES WHERE <cond>`: returns datasources based on condition.
2. `SHOW VIEWS WHERE <cond>`: returns views based on condition.

### CODE REVIEW

**Comment by adeshr** [comment]
cc @vrajat

**Comment by adeshr** [comment]
This change will need release of new version of calcite which contains `SqlShowQuark`. Build fails because of it.

**Comment by vrajat** [comment]
LG. Can you release a new calcite version and get the tests to pass ?

**Comment by adeshr** [comment]
Released new calcite version and tests are passing now.

**Pull request merged**
